[package]
name = "book"
version = "1.0.0"
authors = []

[addresses]
tickets_addr = "6976ec3aa37858aad990b899d5c17ad827b66cab91ccdb7256c12083313deb40"

[dev-addresses]
tickets_addr = "6976ec3aa37858aad990b899d5c17ad827b66cab91ccdb7256c12083313deb40"



[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
